Treehouse.AspNetCore/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Treehouse.AspNetCore.Data;
using Treehouse.AspNetCore.Models;
using Treehouse.AspNetCore.ViewModels;

namespace Treehouse.AspNetCore.Controllers
{
    public class PlayersController : Controller
    {
        private readonly PlayerContext _context;

        public PlayersController(PlayerContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index( string searchString, string teamString)
        {
            var teams = _context.Team2.Select(t => t);
            var teamNames = teams.Select(t => t.TeamName);
            var players = _context.Player.Select(p => p).Include(p => p.Team).OrderBy(p => p.Position).ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                players = players.Where(p => p.Name.Contains(searchString)).ToList();
            }

            if (!String.IsNullOrEmpty(teamString))
            {
                
                players = players.Where(p => p.Team.TeamName == teamString).ToList();
 
            }


                var playerVM = new PlayerViewModel()
                {
                    SelectTeams = new SelectList(await teamNames.Distinct().ToListAsync()),
                    Players = players
                };
            //return View(await _context.Player.ToListAsync());
            return View(playerVM);

        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }
            PlayerViewModel playerViewModel = new PlayerViewModel()
            {
                Player = player
            };
            return View(playerViewModel);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            
            var teams = _context.Team2.ToList();
            //ViewBag.Teams = new SelectList(teams, "ID", "Team name");
            PlayerViewModel playerViewModel = new PlayerViewModel()
            {

                //Player = new Player(),


        };
            //playerViewModel.Teams = _context.Team.ToList();
            ViewBag.Title = "Create";
            return View(playerViewModel);
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Position,Skill,TeamId")] Player player)
        {

            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Position,Skill")] Player player)
        {
            if (id != player.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Player
                .FirstOrDefaultAsync(m => m.Id == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Player.FindAsync(id);
            _context.Player.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Player.Any(e => e.Id == id);
        }
    }
}

Treehouse.AspNetCore/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Treehouse.AspNetCore.Data;
using Treehouse.AspNetCore.Models;
using Treehouse.AspNetCore.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Treehouse.AspNetCore.LiveModels;
using Treehouse.AspNetCore.Services;
using static Treehouse.AspNetCore.Models.League;
using RestApiWrapper;

namespace Treehouse.AspNetCore.Controllers
{
    public class TeamsController : Controller
    {
        private readonly PlayerContext _context;
        private HttpClient _httpClient;
        private string _sorted;
        private static List<Team2> team2s;
        private ITimedUpdateService _timedUpdateService = null;
        private readonly IRestApiRequesterService _restApiRequestService;
        private readonly IUserService _userService;
        public TeamsController(PlayerContext context, IHttpClientFactory clientFactory, ITimedUpdateService timedUpdateService, IUserService userService)
        {
            _context = context;
            _httpClient = clientFactory.CreateClient("nhl");
            _sorted = "";
            team2s = _context.Team2.Select(t => t).Include(t => t.Division).ToList();
            _timedUpdateService = timedUpdateService;
            _userService = userService;
        }

     
        // GET: Teams
        public async Task<IActionResult> Index(string searchString, string teamDivision, string sortOrder, LoginResponseModel loginResponseModel)
        {
            
            _sorted = sortOrder;
            var divisionQuery = _context.Team2.OrderBy(t => t.Division.name).Select(t => t.Division.name).Distinct();
            var teams = _context.Team2.Select(t => t).Include(t => t.Division).ToList();
            //foreach (var team2 in teams)
            //{
            //    var request = new HttpRequestMessage(HttpMethod.Get, $"teams/{team2.Id}/stats");
            //    var response = await _httpClient.SendAsync(request);
            //    var responseStream = await response.Content.ReadAsStringAsync();
            //   // TeamStats.Rootobject test2 = new TeamStats.Rootobject();
            //    if (response.IsSuccessStatusCode)
            //    {
            //        var stats = JsonConvert.DeserializeObject<TeamStats.Rootobject>(responseStream);
            //        team2.Points = stats.stats[0].splits[0].stat.pts.ToString();
            //        team2.GamesPlayed = stats.stats[0].splits[0].stat.gamesPlayed;
            //        //await _context.SaveChangesAsync();

            //    }
            //    //string pts = "";
            //    //int gamesPlayed = 0;
            //    //using (_httpClient)
            //    //{
            //    //    using (var nhlResponse = new HttpClient().GetAsync($"https://statsapi.web.nhl.com/api/v1/teams{team2.Id}/stats"))
            //    //    {
            //    //        string apiResponse = await nhlResponse.Result.Content.ReadAsStringAsync();
            //    //        var test = JsonConvert.DeserializeObject<TeamStats.Rootobject>(apiResponse);
            //    //        pts = test.stats[0].splits[0].stat.pts.ToString();
            //    //        gamesPlayed = test.stats[0].splits[0].stat.gamesPlayed;
            //    //    }
            //    //}

                
            //}
            teams = teams.OrderByDescending(t => t.Points).ToList();
            if (!string.IsNullOrEmpty(_sorted))
            {
                teams = teams.OrderByDescending(t => t.Points).ToList();
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                teams = teams.Where(t => t.name.Contains(searchString)).OrderByDescending(t => t.Points).ToList();
            }

            if (!string.IsNullOrEmpty(teamDivision))
            {
                teams = teams.Where(t => t.Division.name == teamDivision).OrderByDescending(t => t.Points).ToList();
            }

            var teamVM = new TeamViewModel()
            {
                Teamz = teams.ToList(),
                Divisions = new SelectList(await divisionQuery.Distinct().ToListAsync())

            };
            
            //if (loginResponseModel.token != null)
            //{
            //    var response = _restApiRequestService.GetRequest("https://sleepy-falls-59530.herokuapp.com/questions/user", "Bearer", loginResponseModel.token);
            //    if (response.IsSuccessStatusCode)
            //    {
            //        return View(teamVM);
            //    }
            //}
            if (_userService.GetAuth())
            {
                return View(teamVM);
            }
            
            return RedirectToAction("UserLogin", "Users");
        }

        // GET: Teams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stat = "";
            using(var httpClient = new HttpClient())
            {
                using (var response = httpClient.GetAsync($"https://statsapi.web.nhl.com/api/v1/teams/{id}/stats"))
                {
                    string apiResponse = await response.Result.Content.ReadAsStringAsync();
                    var stats = JObject.Parse(apiResponse);
                    stats.Remove("copyright");
                    var test = JsonConvert.DeserializeObject<TeamStats.Rootobject>(apiResponse).stats.ToList();
                    stat = test.FirstOrDefault().splits.FirstOrDefault().stat.pts.ToString();
                }
            }
            
            var team = await _context.Team2.Include(t => t.Division).Include(t => t.Venue)
                .FirstOrDefaultAsync(t => t.Id == id);
            //var team = await _context.Team2
            //    .FirstOrDefaultAsync(m => m.Id == id);
            
            if (team == null)
            {
                return NotFound();
            }
            TeamViewModel teamViewModel = new TeamViewModel()
            {
                Team2 = team,
                Points = stat
            };
            return View(teamViewModel);
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TeamName,Venue")] Treehouse.AspNetCore.Models.League.Team2 team)
        {
            if (ModelState.IsValid)
            {
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var divisionQuery = _context.Team2.OrderBy(t => t.Division).Select(t => t.Division);
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team2.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            TeamViewModel teamViewModel = new TeamViewModel()
            {
                Team2 = team,
                Divisions = new SelectList(await divisionQuery.Distinct().ToListAsync())
            };
            return View(teamViewModel);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TeamName,Location,Division")] Treehouse.AspNetCore.Models.League.Team2 team)
        {
            if (id != team.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var divisionQuery = _context.Team2.OrderBy(t => t.Division).Select(t => t.Division);
            TeamViewModel teamViewModel = new TeamViewModel()
            {
                Team2 = await _context.Team2.FindAsync(id),
                Divisions = new SelectList(await divisionQuery.Distinct().ToListAsync())
            };       
            return View(teamViewModel);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Team2
                .FirstOrDefaultAsync(m => m.Id == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Team2.FindAsync(id);

Treehouse.AspNetCore/Views/Shared/_BusyIndicatorPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="loading">
    Loading&#8230;
</div>

Treehouse.AspNetCore/Views/Shared/_Layout.cshtml
@model Treehouse.AspNetCore.ViewModels.AuthModel.IBaseAuthModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Treehouse.AspNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <partial name="_BusyIndicatorPartial" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Treehouse.AspNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Questions</a>
                        </li>
                        @if (Model != null && Model.IsAuth)
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                Dropdown link
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Link 1</a>
                                <a class="dropdown-item alert-danger" asp-controller="Users" asp-action="Logout">Log out</a>
                                <a class="dropdown-item" href="#">Link 3</a>
                            </div>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Treehouse.AspNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Treehouse.AspNetCore/Views/Shared/_LoggedIn.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">User questions</a>
    </li>